### ISSUE TITLE
S3o workaround

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/n-test#80]
For the smoke tests, it'd be awesome to have a means to test response codes correctly for s3o protected paths.

e.g. right now we have to do `'/': 302`, but really that should be a 200 check.

**Comment by adgad** [comment]
I _think_ you actually can test for a 200 for redirects. The default behaviour for Puppeteer is to follow redirects, so the status is 200. We have to manually check for redirects because a lot of the tests were previously written to check for a 302 because `fetch`.

IIRC, the way this works is:

IF your test is expecting a 302 or a `path`, we'll check the redirects to see if there was a 302.
If your test is expecting a 200, we'll check the final page and status, which should be a 200.
